version: '3.8'

services:
  applo:
    build:
      context: .
      dockerfile: UserServer/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongolo
    environment:
      - MONGO_URI=mongodb://mongo:27017/resource

  mongolo:
    build:
      context: .
      dockerfile: UserServer/Dockerfile.mongo
    ports:
      - "27017:27017"
  
  webapplo:
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - gptgenlo
      - googlelo
      - applo

  gptgenlo:
    build:
      context: .
      dockerfile: Chat-GPT4/Dockerfile
    ports:
      - "4000:4000"

  googlelo:
    build:
      context: .
      dockerfile: GoolgleMap/Dockerfile
    ports:
      - "3000:3000"


      